const CompanyTag = {
  BAA: '네이버',
  BAB: '카카오',
  BAC: '토스',
  BAD: '삼성',
  BAE: '다음',
  BAF: '구글',
  BAG: 'AWS',
  BAH: '국민은행',
  BAI: 'LG',
  BAJ: '라인',
  BAK: 'NHN',
  BAL: '애플',
  BAM: '현대 자동차',
  BAN: '우아한형제들',
  BAO: '필립스',
  BAP: '아틀라시안',
  BAQ: '쿠팡',
  BAR: '당근마켓',
  BAS: 'SKT',
  BAT: '스마일게이트',
  BAU: '야놀자',
  BAV: 'NC소프트',
  BAW: '넷마블',
  BAX: '11번가',
  BAY: '티맥스 소프트',
  BAZ: '넥슨',
  BBA: '티몬',
};
Object.freeze(CompanyTag);

export default CompanyTag;
