const SkillTag = {
  CAA: 'PHP',
  CAB: 'Javascript',
  CAC: 'MYSQL',
  CAD: 'Figma',
  CAE: 'HTML/CSS',
  CAG: 'React.js',
  CAH: 'Vue.js',
  CAI: 'Angular.js',
  CAJ: 'Node.js',
  CAK: 'Scratch',
  CAL: 'Kotlin',
  CAM: 'Visual Basic',
  CAN: 'Next.js',
  CAO: 'SQL',
  CAP: 'Nest.js',
  CAQ: 'Python',
  CAR: 'C',
  CAS: 'C++',
  CAT: 'C#',
  CAU: 'Rust',
  CAV: 'Java',
  CAW: 'Spring',
  CAX: 'Spring Boot',
  CAY: 'JSP',
  CAZ: 'JPA',
  CBA: 'Typescript',
  CBB: 'Go',
  CBC: 'Shell',
  CBD: 'Ruby',
  CBE: 'TensorFlow',
  CBF: 'NoSQL',
  CBG: 'Git',
  CBH: 'Flutter',
  CBI: 'Swift',
  CBJ: 'Django',
  CBK: 'Flask',
  CBL: 'Laravel',
  CBM: 'Bootstrap',
  CBN: '.NET Framework',
  CBO: 'Unity',
  CBP: 'jQuery',
};
Object.freeze(SkillTag);
export default SkillTag;
