const SkillTag = {
  CAA: Symbol('PHP'),
  CAB: Symbol('Javascript'),
  CAC: Symbol('MYSQL'),
  CAD: Symbol('Figma'),
  CAE: Symbol('HTML/CSS'),
  CAG: Symbol('React.js'),
  CAH: Symbol('Vue.js'),
  CAI: Symbol('Angular.js'),
  CAJ: Symbol('Node.js'),
  CAK: Symbol('Scratch'),
  CAL: Symbol('Kotlin'),
  CAM: Symbol('Visual Basic'),
  CAN: Symbol('Next.js'),
  CAO: Symbol('SQL'),
  CAP: Symbol('Nest.js'),
  CAQ: Symbol('Python'),
  CAR: Symbol('C'),
  CAS: Symbol('C++'),
  CAT: Symbol('C#'),
  CAU: Symbol('Rust'),
  CAV: Symbol('Java'),
  CAW: Symbol('Spring'),
  CAX: Symbol('Spring Boot'),
  CAY: Symbol('JSP'),
  CAZ: Symbol('JPA'),
  CBA: Symbol('Typescript'),
  CBB: Symbol('Go'),
  CBC: Symbol('Shell'),
  CBD: Symbol('Ruby'),
  CBE: Symbol('TensorFlow'),
  CBF: Symbol('NoSQL'),
  CBG: Symbol('Git'),
  CBH: Symbol('Flutter'),
  CBI: Symbol('Swift'),
  CBJ: Symbol('Django'),
  CBK: Symbol('Flask'),
  CBL: Symbol('Laravel'),
  CBM: Symbol('Bootstrap'),
  CBN: Symbol('.NET Framework'),
  CBO: Symbol('Unity'),
  CBP: Symbol('jQuery'),
};
Object.freeze(SkillTag);
export default SkillTag;
